# Generated by Django 2.0 on 2017-12-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Бортовой номер')),
                ('type', models.CharField(max_length=200, verbose_name='Модель')),
                ('max_load', models.FloatField(verbose_name='Максимальная грузоподъёмность')),
                ('load', models.FloatField(verbose_name='Текущий вес')),
                ('over_load', models.FloatField(verbose_name='Перегруз %')),
            ],
        ),
    ]
